#ifndef xbmc_keys_h
#define xbmc_keys_h

#include <kbrd_codes.h>

#define XBMC_AUDIODELAY						KEYCODE_A
#define XBMC_SCHEDULERECORDINGTIMERS		KEYCODE_B
#define XBMC_CONTEXTUALMENU					KEYCODE_C
#define XBMC_MOVEDOWN						KEYCODE_D
#define XBMC_EPGTVGUIDE						KEYCODE_E
#define XBMC_FASTFORWARD					KEYCODE_F
#define XBMC_CHANNELSWINDOW					KEYCODE_H
#define XBMC_INFO							KEYCODE_I
#define XBMC_RADIOCHANNELSWINDOW			KEYCODE_J
#define XBMC_RECORDINGSWINDOW				KEYCODE_K
#define XBMC_NEXTSUBTITLE					KEYCODE_L
#define XBMC_LOCKPRESET						KEYCODE_L
#define XBMC_NOWPLAYING						KEYCODE_N
#define XBMC_PLAYERCONTROLS					KEYCODE_M
#define XBMC_DIAGNOSTICINFO					KEYCODE_O
#define XBMC_PLAY							KEYCODE_P
#define XBMC_QUEUE							KEYCODE_Q
#define XBMC_REWIND							KEYCODE_R
#define XBMC_SHUTDOWNMENU					KEYCODE_S
#define XBMC_TOGGLESUBTITLES				KEYCODE_T
#define XBMC_MARKEDASWATCHED				KEYCODE_W
#define XBMC_STOP							KEYCODE_X
#define XBMC_PAUSE_PLAY						KEYCODE_SPACE
#define XBMC_LEFT							KEYCODE_ARROW_LEFT
#define XBMC_RIGHT							KEYCODE_ARROW_RIGHT
#define XBMC_UP								KEYCODE_ARROW_UP
#define XBMC_DOWN							KEYCODE_ARROW_DOWN
#define XBMC_PAGEUP							KEYCODE_PAGE_UP
#define XBMC_PAGEDOWN						KEYCODE_PAGE_DOWN
#define XBMC_SELECT							KEYCODE_ENTER
#define XBMC_BACK							KEYCODE_BACKSPACE
#define XBMC_ZOOM							KEYCODE_Z
#define XBMC_PREVIOUSMENU_HOMESCREEN		KEYCODE_ESC
#define XBMC_SKIPFORWARD					KEYCODE_PERIOD
#define XBMC_SKIPBACKWARD					KEYCODE_COMMA
#define XBMC_FULLSCREENMODE					KEYCODE_TAB
#define XBMC_SCREENSHOT						KEYCODE_PRINTSCREEN
#define XBMC_VOLUMEDOWN						KEYCODE_MINUS
#define XBMC_VOLUMEUP						KEYCODE_EQUAL
#define XBMC_TOGGLEAPPLWINDOWEDMODE			KEYCODE_BACKSLASH
#define XBMC_STEPFORWARD10MIN				KEYCODE_BRACKET_LEFT
#define XBMC_STEPBACKWARD10MIN				KEYCODE_BRACKET_RIGHT
#define XBMC_EXITXBMCEDEN					KEYCODE_END
#define XBMC_EXITXBMCFRODO					0x4D000101 // ctrl+end
#define XBMC_DELETEFILE_REMOVEFROMPLAYLIST	KEYCODE_DELETE

#endif